interface KeyboardMap {
  [keyCode: string]: string;
}

const keyboardMap: KeyboardMap = {
  "0": "jump to the start of the line",
  "%": "move to matching character (default supported pairs: '()', '{}', '[]'. use :h matchpairs in vim for more info)",
  "^": "jump to the first non-blank character of the line",
  "}": "jump to next paragraph (or function/block, when editing code)",
  "{": "jump to previous paragraph (or function/block, when editing code)",
  ";": "repeat previous f, t, F or T movement",
  ",": "repeat previous f, t, F or T movement, backwards",
  ".": "repeat last command",
  ">": "(visual mode) shift text right",
  "<": "(visual mode) shift text left",
  "~": "(visual mode) switch case",
  $: "jump to the end of the line",
  a: "insert (append) after the cursor",
  A: "insert (append) at the end of the line",
  b: "jump backwards to the start of a word",
  B: "jump backwards to the start of a word (words can contain punctuation)",
  c: "change operator",
  C: "change (replace) to the end of the line",
  d: "delete operator/(visual mode) delete marked text",
  dd: "delete an entire line",
  dw: "delete a word",
  D: "delete (cut) to the end of the line",
  e: "jump forwards to the end of a word",
  E: "jump forwards to the end of a word (words can contain punctuation)",
  g: "goto operator",
  G: "go to the last line of the document",
  h: "move cursor left",
  H: "move to top of screen",
  i: "insert before the cursor",
  I: "insert at the beginning of the line",
  j: "move cursor down",
  J: "join line below to the current one with one space in between",
  k: "move cursor up",
  K: "open man page for word under the cursor",
  l: "move cursor right",
  L: "move to bottom of screen",
  M: "move to middle of screen",
  n: "repeat search in same direction",
  N: "repeat search in opposite direction",
  o: "append (open) a new line below the current line",
  O: "append (open) a new line above the current line",
  p: "put (paste) the clipboard after cursor",
  P: "put (paste) before cursor",
  q: "stop recording macro",
  r: "replace a single character",
  R: "replace more than one character, until ESC is pressed",
  s: "delete character and substitute text",
  S: "delete line and substitute text (same as cc)",
  u: "undo/(visual mode) change marked text to lowercase",
  U: "restore (undo) last changed line/(visual mode) change marked text to uppercase",
  v: "start visual mode, mark lines, then do a command (like y-yank)",
  V: "start linewise visual mode",
  w: "jump forwards to the start of a word",
  W: "jump forwards to the start of a word (words can contain punctuation)",
  x: "delete (cut) character",
  y: "yank (copy) operator/(visual mode) yank marked text",
};

export default keyboardMap;
